language: python
sudo: required  # for gdb installation
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "3.8-dev"
  - "pypy"

matrix:
  allow_failures:
    - python: '3.7-dev'
    - python: '3.8-dev'

before_install:
  - sudo apt-get install gdb

install:
  - 'pip install -e .[dev]'

script:
  - make test

cache:
    directories:
        # avoid using PyPI's bandwidth when pip packages are already cached
        - $HOME/.cache/pip
